---
- name: Ping hosts
  hosts: SW1
  gather_facts: no
  connection: network_cli
  vars:
    ansible_user: pfe
    ansible_password: pfe
    ansible_network_os: ios
  tasks:
    - name: Ping hosts
      ping:
