---
- name: Vérification de l'état du routeur
  hosts: R1
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: ios
    ansible_user: pfe
    ansible_password: pfe

  tasks:

    - name: Vérifier les interfaces
      ios_command:
        commands:
          - show ip interface brief
      register: output_interfaces

    - name: Afficher les interfaces
      debug:
        var: output_interfaces.stdout_lines


