---
- name: Configuration des adresses IP pour les VLANs existants
  hosts: SW1
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: ios
    ansible_user: pfe
    ansible_password: pfe

  tasks:
    - name: Configuration de l'adresse IP pour VLAN 2
      ios_config:
        lines:
          - interface vlan 2
          - ip address 10.0.0.1 255.255.255.0
    - name: Configuration de l'adresse IP pour VLAN 3
      ios_config:
        lines:
          - interface vlan 3
          - ip address 11.0.0.1 255.255.255.0

