- name: Clean up resources
  hosts: localhost
  gather_facts: false
  vars:
    molecule_instance_names:
      - instance_name_1
      - instance_name_2
      # Ajoutez les noms des instances selon votre configuration
  tasks:
    # Ajoutez ici les tâches de nettoyage nécessaires pour supprimer les ressources créées pendant le test.
    # Par exemple, si vous devez arrêter et supprimer des services, des fichiers, des machines virtuelles, etc.
    # Assurez-vous que les tâches ci-dessous correspondent à votre environnement spécifique.
    - name: Example task to clean up resources
      # Ajoutez ici les tâches de nettoyage nécessaires
      debug:
        msg: "Cleaning up resource {{ item }}"
      with_items: "{{ molecule_instance_names }}"

