dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

driver:
    name: docker

platforms:
  - name: molecule-ubuntu
    image: ubuntu:18.04
    pre_build_image: true

provisioner:
  name: ansible
  lint: |
    set -e
    ansible-lint

scenario:
  name: default
  test_sequence:
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy

verifier:
  name: testinfra
  options:
    - -v
