--
dependency:
  name: galaxy
  options:
    requirements-file: molecule/default/requirements.yml

driver:
  name: delegated  # Utilisation du driver par défaut (delegated) pour les tests

platforms:
  - name: molecule-ubuntu
    image: ubuntu:20.04
    pre_build_image: true

provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: default
  test_sequence:
    - dependency
    - lint
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy

verifier:
  name: testinfra
  lint:
    name: flake8
