name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible
        pip install molecule[docker]
        pip install docker

    - name: Clean up Docker
      run: |
        docker system prune -af

    - name: Lint Ansible playbooks
      run: |
        ansible-lint

    - name: Test Ansible roles with Molecule
      run: |
        molecule --debug test
